### ISSUE TITLE
Plan the "production" deployment configuration for Soy

### ISSUE THREAD

**Issue by breakpointer** [ConsenSys/web3studio-soy#41]
## Overview

Propose a plan to configure aws accounts, users, roles, such that we can feel comfortable using this setup to deploy "production" versions of our projects. 

### Reference
"The Plan" lives as a living post in the first https://github.com/ConsenSys/web3studio-soy/issues/41#issuecomment-456474954

### Questions

- Do we need two accounts or is IAM good enough?

### Assumptions

- Developer accounts should not be allowed to change production assets 
- Developers should be able to change production assets in an emergency
- Travis should be able to change production
- Some kind of integration test suite should exist or be possible
- Developer accounts should be able to see production logs
- uptime monitoring should be in place. 
    - Downtime alerts sent via slack

### Acceptance

- Documented plan for soy in production

## Tasks

- [ ] A list of tasks that need
- [ ] to be done to call this issue done

**Comment by barlock** [comment]
## The Plan

### Permissioning

### Monitoring

### Deployments

**Comment by breakpointer** [comment]
We should also add 3rd party monitoring through Pingdom. I think they might still have a free version for monitoring a single site. Any downtime alerts from pingdom should be sent to the web3studio gmail group.

**Comment by breakpointer** [comment]
For the question about how to isolate the production deployment... I've done this with multiple AWS accounts. This provides the most isolation. However, I'm not sure how much effort there is to get a new production-only AWS account tied to the master Consensys billing org. It might be less of a hassle to deploy prod and dev/test in the same AWS account but use different user accounts for each one. Security and configuration wise both options are the same (two accounts vs one account). Having two separate accounts makes billing and cost accounting easier such that might be worth enough to justify the effort to set up the prod-only AWS account. 

Going with the prod IAM user accounts inside the single prod/dev/test AWS account we'd probably want to setup different users for 'prod'. This would not offer much in the way of security because everyone on our team would have an account anyway but it could help prevent accidental changes to production.  I'd imagine we'd have users like 'username' for dev/test and 'username-prod' for production only. There would need to be a separate production role and this role would have full access to all production resources and nothing else. Likewise the dev/test IAM users would not be allowed to add the production role/access

**Comment by barlock** [comment]
> We should also add 3rd party monitoring through Pingdom. I think they might still have a free version for monitoring a single site. 

It doesn't look like they have a free version 😢. 

Are you thinking that a third party is better so the infrastructure isn't tied to a single provider? What features are you looking for in a third party over just aws? I've used Pingdom, it's great, lots of awesome features that aws doesn't have. New Relic I've also had really good experiences with. 

My gut here is that the added hassle of figuring out how to pay for a third party that isn't AWS will be more pain than it's worth (yet).

**Comment by breakpointer** [comment]
Pingdom also has helpful performance metrics based on lighthouse. Here's a manual run of the site https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fconsensys.net%2Fweb3studio%2F

**Comment by barlock** [comment]
Awesome. Yeah lighthouse is great and having the option to ping from
multiple regions would be cool.

I like the idea of throwing it on your account and then working it to a
Consensys one later. It will let us prove out it's usefulness while we wait
for all the things to line up.

**Comment by barlock** [comment]
@breakpointer Looking at the [pingdom pricing](https://www.pingdom.com/pricing/) you need the `Standard` plan for alerting. Do you have a plan that enables that?

I'm thinking for now we wire up both route53 health checks (for alerting) and pingdom (for better information). If we can get just a larger paid plan, we can switch to just pingdom.

Ideally, i'd like to get our configuration as code. Pingdom does have an [API](https://www.pingdom.com/?api=2.1/) but it looks like it would require some scripting. I'm a bit surprised I'm not able to find any projects that do it for you in a CI environment! There is a pretty cool k8s [ingress monitor](https://medium.com/stakater/automating-uptime-monitoring-on-kubernetes-with-pingdom-6a40977f82e1) that automates it... but that isn't helpful for us right now.

**Comment by humbitious** [comment]
Advise going with Amazon for now and upping to pingdom after experimental phase.

**Comment by breakpointer** [comment]
Sounds good.  I have added our site to my personal pingdom (I have the "Starter" plan at $14/mo). This is enough CYA for me to sleep better at night (or not sleep... if the site goes down). 

Also, I'm not sure your comment about needing the 'standard' plan for alerting @barlock That is not my understanding and I don't see anything on the subscription page to that effect.

**Comment by barlock** [comment]
I could be misreading, it says `Threshold alerting` isn't included in standard. 

Is it possible to get those notifications sent into the alarms channel? I'd be curious to see what it catches that amazon doesn't.

**Comment by breakpointer** [comment]
Oh, perhaps that's for setting some custom threshold on something like response time. For what I have set up it really is just "uptime" alerting. I get emails/SMS about the site being down. Oh, and performance alerting for slow load times... But with my plan I only get performance monitoring on one site.

**Comment by breakpointer** [comment]
The whole reason I wanted something like pingdom is just uptime. It's important to have something other than your own tooling/system/host telling you that everything is okay.

**Comment by breakpointer** [comment]
> Is it possible to get those notifications sent into the alarms channel? I'd be curious to see what it catches that amazon doesn't.

My options are SMS or email and I think with my account type they can only go to me.

**Comment by barlock** [comment]
> The whole reason I wanted something like pingdom is just uptime alerting (although their performance stuff is pretty neat and I've found it very useful). From my experience I have learned that it's important to have something other than your own tooling/system/host telling you that everything is okay.

I couldn't agree more. Have you seen what Route53+CloudWatch gives us? It pings our endpoints every 30 seconds (from a bunch of regions) and if it fails if it doesn't get a success response 3 times. Upon failure, it notifies our slack alarms channel. 
It also measures TTFB and SSL Handshake time.

Here are the charts https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#cw:dashboard=Route53

> My options are SMS or email and I think with my account type they can only go to me.

Email is fine, slack has an integration that lets you forward notifications to a channel. That's [what I'm using](https://github.com/ConsenSys/web3studio-website/pull/12/files#diff-8ae1ffe6592abcee68917e0aca1bdc68R28) for the aws checks as well. I can send you that address offline.
